name: my-notebook-env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jupyterlab-git  >=0.34  
  - jupyterlab >=3,<4
  - git
  - python >=3.9,<3.10 # for example
  - geopandas          # for example, brings in pandas, numpy, gdal, etc.
  - ipyleaflet         # for example, brings in ipywidgets, etc
